"""
This type stub file was generated by pyright.
"""

from collections.abc import Generator, ItemsView, MutableMapping
from typing import Any

class CaseInsensitiveDict(MutableMapping[str, str]):
    """A case-insensitive ``dict``-like object.

    Implements all methods and operations of
    ``MutableMapping`` as well as dict's ``copy``. Also
    provides ``lower_items``.

    All keys are expected to be strings. The structure remembers the
    case of the last key to be set, and ``iter(instance)``,
    ``keys()``, ``items()``, ``iterkeys()``, and ``iteritems()``
    will contain case-sensitive keys. However, querying and contains
    testing is case insensitive::

        cid = CaseInsensitiveDict()
        cid['Accept'] = 'application/json'
        cid['aCCEPT'] == 'application/json'  # True
        list(cid) == ['Accept']  # True

    For example, ``headers['content-encoding']`` will return the
    value of a ``'Content-Encoding'`` response header, regardless
    of how the header name was originally stored.

    If the constructor, ``.update``, or equality comparison
    operations are given keys that have equal ``.lower()``s, the
    behavior is undefined.
    """

    def __init__(self, data: Any = ..., **kwargs: Any) -> None: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Generator[Any]: ...
    def __len__(self) -> int: ...
    def lower_items(self) -> Generator[tuple[Any, Any]]: ...
    """Like iteritems(), but with all lowercase keys."""

    def __eq__(self, other: object) -> bool: ...
    def copy(self) -> CaseInsensitiveDict: ...
    def items(self) -> ItemsView[Any, Any]: ...
