# Copyright (c) 2026 Gerrrt
# Licensed under the MIT License

from collections.abc import Generator, ItemsView, MutableMapping
from typing import Any

class CaseInsensitiveDict(MutableMapping[str, str]):
    def __init__(self, data: dict[str, str] | None = None, **kwargs: str) -> None: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Generator[Any]: ...
    def __len__(self) -> int: ...
    def lower_items(self) -> Generator[tuple[Any, Any]]: ...
    def __eq__(self, other: object) -> bool: ...
    def copy(self) -> CaseInsensitiveDict: ...
    def items(self) -> ItemsView[Any, Any]: ...
