"""
This type stub file was generated by pyright.
"""

from playwright import async_api, sync_api
from playwright.async_api._context_manager import (
    PlaywrightContextManager as AsyncPlaywrightContextManager,
)
from playwright.sync_api._context_manager import (
    PlaywrightContextManager as SyncPlaywrightContextManager,
)

class AsyncWrappingContextManager:
    def __init__(
        self, stealth: object, manager: AsyncPlaywrightContextManager
    ) -> None: ...
    async def __aenter__(self) -> async_api.Playwright: ...
    async def start(self) -> async_api.Playwright: ...
    async def __aexit__(self, *args: object) -> None: ...

class SyncWrappingContextManager:
    def __init__(
        self, stealth: object, manager: SyncPlaywrightContextManager
    ) -> None: ...
    def __enter__(self) -> sync_api.Playwright: ...
    def start(self) -> sync_api.Playwright: ...
    def __exit__(self, *args: object) -> None: ...
