# Copyright (c) 2026 Gerrrt
# Licensed under the MIT License

from collections.abc import Generator
from dataclasses import dataclass
from typing import Any

from playwright.async_api import Page as AsyncPage
from playwright.sync_api import Page as SyncPage

def from_file(name: str) -> str: ...

SCRIPTS: dict[str, str] = ...

@dataclass
class StealthConfig:
    webdriver: bool = ...
    webgl_vendor: bool = ...
    chrome_app: bool = ...
    chrome_csi: bool = ...
    chrome_load_times: bool = ...
    chrome_runtime: bool = ...
    iframe_content_window: bool = ...
    media_codecs: bool = ...
    navigator_hardware_concurrency: int = ...
    navigator_languages: bool = ...
    navigator_permissions: bool = ...
    navigator_platform: bool = ...
    navigator_plugins: bool = ...
    navigator_user_agent: bool = ...
    navigator_user_agent_data: bool = ...
    navigator_vendor: bool = ...
    outerdimensions: bool = ...
    hairline: bool = ...
    vendor: str = ...
    renderer: str = ...
    nav_vendor: str = ...
    nav_user_agent: str = ...
    nav_platform: str = ...
    languages: tuple[str] = ...
    runoninsecureorigins: bool | None = ...
    @property
    def enabled_scripts(self) -> Generator[str, Any]: ...

def stealth_sync(page: SyncPage, config: StealthConfig = ...) -> None: ...
async def stealth_async(page: AsyncPage, config: StealthConfig = ...) -> None: ...
